In [1]:
import numpy as np
import pandas as pd

In [2]:
movies=pd.read_csv('/content/drive/MyDrive/Colab Notebooks/ML DL PROJECTS/tmdb_5000_movies.csv')
credits=pd.read_csv('/content/drive/MyDrive/Colab Notebooks/ML DL PROJECTS/tmdb_5000_credits.csv')

In [3]:
movies.head()

,budget,genres,homepage,id,keywords,original_language,original_title,overview,popularity,production_companies,production_countries,release_date,revenue,runtime,spoken_languages,status,tagline,title,vote_average,vote_count
0,237000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://www.avatarmovie.com/,19995,"[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...",en,Avatar,"In the 22nd century, a paraplegic Marine is di...",150.437577,"[{""name"": ""Ingenious Film Partners"", ""id"": 289...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2009-12-10,2787965087,162.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}, {""iso...",Released,Enter the World of Pandora.,Avatar,7.2,11800
1,300000000,"[{""id"": 12, ""name"": ""Adventure""}, {""id"": 14, ""...",http://disney.go.com/disneypictures/pirates/,285,"[{""id"": 270, ""name"": ""ocean""}, {""id"": 726, ""na...",en,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...",139.082615,"[{""name"": ""Walt Disney Pictures"", ""id"": 2}, {""...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2007-05-19,961000000,169.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,"At the end of the world, the adventure begins.",Pirates of the Caribbean: At World's End,6.9,4500
2,245000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://www.sonypictures.com/movies/spectre/,206647,"[{""id"": 470, ""name"": ""spy""}, {""id"": 818, ""name...",en,Spectre,A cryptic message from Bond’s past sends him o...,107.376788,"[{""name"": ""Columbia Pictures"", ""id"": 5}, {""nam...","[{""iso_3166_1"": ""GB"", ""name"": ""United Kingdom""...",2015-10-26,880674609,148.0,"[{""iso_639_1"": ""fr"", ""name"": ""Fran\u00e7ais""},...",Released,A Plan No One Escapes,Spectre,6.3,4466
3,250000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 80, ""nam...",http://www.thedarkknightrises.com/,49026,"[{""id"": 849, ""name"": ""dc comics""}, {""id"": 853,...",en,The Dark Knight Rises,Following the death of District Attorney Harve...,112.312950,"[{""name"": ""Legendary Pictures"", ""id"": 923}, {""...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2012-07-16,1084939099,165.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,The Legend Ends,The Dark Knight Rises,7.6,9106
4,260000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://movies.disney.com/john-carter,49529,"[{""id"": 818, ""name"": ""based on novel""}, {""id"":...",en,John Carter,"John Carter is a war-weary, former military ca...",43.926995,"[{""name"": ""Walt Disney Pictures"", ""id"": 2}]","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2012-03-07,284139100,132.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,"Lost in our world, found in another.",John Carter,6.1,2124

In [4]:
movies_db=movies.merge(credits,on='title')
movies_db.shape

(4809, 23)

In [5]:
movies_db=movies_db[['movie_id','title','overview','genres','keywords','cast','crew']]
movies_db.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4809 entries, 0 to 4808
Data columns (total 7 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   movie_id  4809 non-null   int64
 1   title     4809 non-null   object
 2   overview  4806 non-null   object
 3   genres    4809 non-null   object
 4   keywords  4809 non-null   object
 5   cast      4809 non-null   object
 6   crew      4809 non-null   object
dtypes: int64(1), object(6)
memory usage: 263.1+ KB

In [6]:
movies_db.isnull().sum()

movie_id    0
title       0
overview    3
genres      0
keywords    0
cast        0
crew        0
dtype: int64

In [7]:
movies_db.dropna(inplace=True)
movies_db.isnull().sum()

movie_id    0
title       0
overview    0
genres      0
keywords    0
cast        0
crew        0
dtype: int64

In [8]:
movies_db.duplicated().sum()

np.int64(0)

In [9]:
movies_db.iloc[0].genres

'[{"id": 28, "name": "Action"}, {"id": 12, "name": "Adventure"}, {"id": 14, "name": "Fantasy"}, {"id": 878, "name": "Science Fiction"}]'

In [10]:
import ast
def convert(obj):
  L=list()
  for i in ast.literal_eval(obj):
    L.append(i['name'])
  return L

In [11]:
movies_db['genres']=movies_db['genres'].apply(convert)

In [12]:
movies_db['genres']

0       [Action, Adventure, Fantasy, Science Fiction]
1                        [Adventure, Fantasy, Action]
2                          [Action, Adventure, Crime]
3                    [Action, Crime, Drama, Thriller]
4                [Action, Adventure, Science Fiction]
                            ...
4804                        [Action, Crime, Thriller]
4805                                [Comedy, Romance]
4806               [Comedy, Drama, Romance, TV Movie]
4807                                               []
4808                                    [Documentary]
Name: genres, Length: 4806, dtype: object

In [13]:
movies_db['keywords']=movies_db['keywords'].apply(convert)
movies_db['keywords']

0       [culture clash, future, space war, space colon...
1       [ocean, drug abuse, exotic island, east india ...
2       [spy, based on novel, secret agent, sequel, mi...
3       [dc comics, crime fighter, terrorist, secret i...
4       [based on novel, mars, medallion, space travel...
                              ...
4804    [united states–mexico barrier, legs, arms, pap...
4805                                                   []
4806    [date, love at first sight, narration, investi...
4807                                                   []
4808            [obsession, camcorder, crush, dream girl]
Name: keywords, Length: 4806, dtype: object

In [14]:
import ast
def convertCast(obj):
  L=list()
  counter=0
  for i in ast.literal_eval(obj):
    if counter!=3:
      L.append(i['name'])
      counter=counter+1
    else:
      break;
  return L

movies_db['cast']=movies_db['cast'].apply(convertCast)
movies_db['cast']

0        [Sam Worthington, Zoe Saldana, Sigourney Weaver]
1           [Johnny Depp, Orlando Bloom, Keira Knightley]
2            [Daniel Craig, Christoph Waltz, Léa Seydoux]
3            [Christian Bale, Michael Caine, Gary Oldman]
4          [Taylor Kitsch, Lynn Collins, Samantha Morton]
                              ...
4804    [Carlos Gallardo, Jaime de Hoyos, Peter Marqua...
4805         [Edward Burns, Kerry Bishé, Marsha Dietlein]
4806           [Eric Mabius, Kristin Booth, Crystal Lowe]
4807            [Daniel Henney, Eliza Coupe, Bill Paxton]
4808    [Drew Barrymore, Brian Herzlinger, Corey Feldman]
Name: cast, Length: 4806, dtype: object

In [15]:
def fetch_director(obj):
  L=list()
  for i in ast.literal_eval(obj):
    if i['job']=='Director':
      L.append(i['name'])
      break;
  return L

movies_db['crew']=movies_db['crew'].apply(fetch_director)
movies_db['crew']

0           [James Cameron]
1          [Gore Verbinski]
2              [Sam Mendes]
3       [Christopher Nolan]
4          [Andrew Stanton]
               ...
4804     [Robert Rodriguez]
4805         [Edward Burns]
4806          [Scott Smith]
4807          [Daniel Hsia]
4808     [Brian Herzlinger]
Name: crew, Length: 4806, dtype: object

In [16]:
movies_db['overview']=movies_db['overview'].apply(lambda x:x.split())
movies_db['overview']

0       [In, the, 22nd, century,, a, paraplegic, Marin...
1       [Captain, Barbossa,, long, believed, to, be, d...
2       [A, cryptic, message, from, Bond’s, past, send...
3       [Following, the, death, of, District, Attorney...
4       [John, Carter, is, a, war-weary,, former, mili...
                              ...
4804    [El, Mariachi, just, wants, to, play, his, gui...
4805    [A, newlywed, couple's, honeymoon, is, upended...
4806    ["Signed,, Sealed,, Delivered", introduces, a,...
4807    [When, ambitious, New, York, attorney, Sam, is...
4808    [Ever, since, the, second, grade, when, he, fi...
Name: overview, Length: 4806, dtype: object

In [17]:
movies_db.head()

,movie_id,title,overview,genres,keywords,cast,crew
0,19995,Avatar,"[In, the, 22nd, century,, a, paraplegic, Marin...","[Action, Adventure, Fantasy, Science Fiction]","[culture clash, future, space war, space colon...","[Sam Worthington, Zoe Saldana, Sigourney Weaver]",[James Cameron]
1,285,Pirates of the Caribbean: At World's End,"[Captain, Barbossa,, long, believed, to, be, d...","[Adventure, Fantasy, Action]","[ocean, drug abuse, exotic island, east india ...","[Johnny Depp, Orlando Bloom, Keira Knightley]",[Gore Verbinski]
2,206647,Spectre,"[A, cryptic, message, from, Bond’s, past, send...","[Action, Adventure, Crime]","[spy, based on novel, secret agent, sequel, mi...","[Daniel Craig, Christoph Waltz, Léa Seydoux]",[Sam Mendes]
3,49026,The Dark Knight Rises,"[Following, the, death, of, District, Attorney...","[Action, Crime, Drama, Thriller]","[dc comics, crime fighter, terrorist, secret i...","[Christian Bale, Michael Caine, Gary Oldman]",[Christopher Nolan]
4,49529,John Carter,"[John, Carter, is, a, war-weary,, former, mili...","[Action, Adventure, Science Fiction]","[based on novel, mars, medallion, space travel...","[Taylor Kitsch, Lynn Collins, Samantha Morton]",[Andrew Stanton]

In [18]:
movies_db['genres']=movies_db['genres'].apply(lambda x:[i.replace(" ","") for i in x])
movies_db['genres']

0       [Action, Adventure, Fantasy, ScienceFiction]
1                       [Adventure, Fantasy, Action]
2                         [Action, Adventure, Crime]
3                   [Action, Crime, Drama, Thriller]
4                [Action, Adventure, ScienceFiction]
                            ...
4804                       [Action, Crime, Thriller]
4805                               [Comedy, Romance]
4806               [Comedy, Drama, Romance, TVMovie]
4807                                              []
4808                                   [Documentary]
Name: genres, Length: 4806, dtype: object

In [19]:
movies_db['keywords']=movies_db['keywords'].apply(lambda x:[i.replace(" ","") for i in x])
movies_db['cast']=movies_db['cast'].apply(lambda x:[i.replace(" ","") for i in x])
movies_db['crew']=movies_db['crew'].apply(lambda x:[i.replace(" ","") for i in x])
#movies_db['keywords']
#movies_db['cast']
#movies_db['crew']

In [20]:
movies_db.head()

,movie_id,title,overview,genres,keywords,cast,crew
0,19995,Avatar,"[In, the, 22nd, century,, a, paraplegic, Marin...","[Action, Adventure, Fantasy, ScienceFiction]","[cultureclash, future, spacewar, spacecolony, ...","[SamWorthington, ZoeSaldana, SigourneyWeaver]",[JamesCameron]
1,285,Pirates of the Caribbean: At World's End,"[Captain, Barbossa,, long, believed, to, be, d...","[Adventure, Fantasy, Action]","[ocean, drugabuse, exoticisland, eastindiatrad...","[JohnnyDepp, OrlandoBloom, KeiraKnightley]",[GoreVerbinski]
2,206647,Spectre,"[A, cryptic, message, from, Bond’s, past, send...","[Action, Adventure, Crime]","[spy, basedonnovel, secretagent, sequel, mi6, ...","[DanielCraig, ChristophWaltz, LéaSeydoux]",[SamMendes]
3,49026,The Dark Knight Rises,"[Following, the, death, of, District, Attorney...","[Action, Crime, Drama, Thriller]","[dccomics, crimefighter, terrorist, secretiden...","[ChristianBale, MichaelCaine, GaryOldman]",[ChristopherNolan]
4,49529,John Carter,"[John, Carter, is, a, war-weary,, former, mili...","[Action, Adventure, ScienceFiction]","[basedonnovel, mars, medallion, spacetravel, p...","[TaylorKitsch, LynnCollins, SamanthaMorton]",[AndrewStanton]

In [21]:
movies_db['tags']=movies_db['overview']+movies_db['genres']+movies_db['keywords']+movies_db['cast']+movies_db['crew']
new_df=movies_db[['movie_id','title','tags']]
new_df.head()

,movie_id,title,tags
0,19995,Avatar,"[In, the, 22nd, century,, a, paraplegic, Marin..."
1,285,Pirates of the Caribbean: At World's End,"[Captain, Barbossa,, long, believed, to, be, d..."
2,206647,Spectre,"[A, cryptic, message, from, Bond’s, past, send..."
3,49026,The Dark Knight Rises,"[Following, the, death, of, District, Attorney..."
4,49529,John Carter,"[John, Carter, is, a, war-weary,, former, mili..."

In [22]:
new_df['tags']=new_df['tags'].apply(lambda x:" ".join(x))
#new_df['tags']=new_df['tags'].apply(lambda x:x.lower())
new_df.head()

/tmp/ipython-input-655061944.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  new_df['tags']=new_df['tags'].apply(lambda x:" ".join(x))

,movie_id,title,tags
0,19995,Avatar,"In the 22nd century, a paraplegic Marine is di..."
1,285,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha..."
2,206647,Spectre,A cryptic message from Bond’s past sends him o...
3,49026,The Dark Knight Rises,Following the death of District Attorney Harve...
4,49529,John Carter,"John Carter is a war-weary, former military ca..."

In [23]:
new_df['tags']=new_df['tags'].apply(lambda x:x.lower())
new_df.head()

/tmp/ipython-input-510464446.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  new_df['tags']=new_df['tags'].apply(lambda x:x.lower())

,movie_id,title,tags
0,19995,Avatar,"in the 22nd century, a paraplegic marine is di..."
1,285,Pirates of the Caribbean: At World's End,"captain barbossa, long believed to be dead, ha..."
2,206647,Spectre,a cryptic message from bond’s past sends him o...
3,49026,The Dark Knight Rises,following the death of district attorney harve...
4,49529,John Carter,"john carter is a war-weary, former military ca..."

To implement Stemming importing nltk

In [24]:
import nltk

In [25]:
from nltk.stem.porter import PorterStemmer
ps=PorterStemmer()

In [26]:
def Stem(text):
  y=list()

  for i in text.split():
    y.append(ps.stem(i))

  return " ".join(y)

In [27]:
new_df['tags']=new_df['tags'].apply(Stem)

/tmp/ipython-input-2738287142.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  new_df['tags']=new_df['tags'].apply(Stem)

In [28]:
from sklearn.feature_extraction.text import CountVectorizer
cv=CountVectorizer(max_features=5000,stop_words='english')
vectors=cv.fit_transform(new_df['tags']).toarray()
vectors

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]])

In [29]:
cv.get_feature_names_out()

array(['000', '007', '10', ..., 'zone', 'zoo', 'zooeydeschanel'],
      dtype=object)

In [30]:
vectors.shape

(4806, 5000)

In [31]:
print(cv.get_feature_names_out()[:500])

['000' '007' '10' '100' '11' '12' '13' '14' '15' '16' '17' '17th' '18'
 '18th' '18thcenturi' '19' '1910' '1920' '1930' '1940' '1944' '1950'
 '1950s' '1960' '1960s' '1970' '1970s' '1971' '1974' '1976' '1980' '1985'
 '1990' '1999' '19th' '19thcenturi' '20' '200' '2003' '2009' '20th' '21st'
 '23' '24' '25' '30' '300' '3d' '40' '50' '500' '60' '70' '80' 'aaron'
 'aaroneckhart' 'abandon' 'abduct' 'abigailbreslin' 'abil' 'abl' 'aboard'
 'abov' 'abus' 'academ' 'academi' 'accept' 'access' 'accid' 'accident'
 'acclaim' 'accompani' 'accomplish' 'account' 'accus' 'ace' 'achiev'
 'acquaint' 'act' 'action' 'actionhero' 'activ' 'activist' 'activities'
 'actor' 'actress' 'actual' 'ad' 'adam' 'adamsandl' 'adamshankman' 'adapt'
 'add' 'addict' 'adjust' 'admir' 'admit' 'adolesc' 'adopt' 'ador'
 'adrienbrodi' 'adult' 'adultanim' 'adulteri' 'adulthood' 'advanc'
 'adventur' 'adventure' 'adventures' 'advertis' 'advic' 'advis' 'affair'
 'affect' 'afghanistan' 'africa' 'african' 'africanamerican'
 'aftercreditssting' 'afterlif' 'aftermath' 'ag' 'age' 'agediffer' 'agenc'
 'agency' 'agenda' 'agent' 'agents' 'aggress' 'ago' 'agre' 'ahead' 'aid'
 'aidanquinn' 'ail' 'aim' 'air' 'airplan' 'airplanecrash' 'airport' 'aka'
 'al' 'alabama' 'alan' 'alaska' 'albert' 'alcatraz' 'alcohol'
 'alecbaldwin' 'alex' 'alexkendrick' 'alfredhitchcock' 'alfredmolina'
 'ali' 'alic' 'alice' 'alien' 'alieninvas' 'alienlife' 'alienplanet'
 'aliens' 'alik' 'aliv' 'alive' 'allen' 'alli' 'allianc' 'allow' 'alon'
 'alongsid' 'alpacino' 'alpha' 'alreadi' 'alter' 'altern' 'alway' 'alyssa'
 'alzheimer' 'amanda' 'amandapeet' 'amandaseyfri' 'amateur' 'amaz'
 'ambassador' 'ambit' 'ambiti' 'ambul' 'ambush' 'america' 'american'
 'americanabroad' 'americancivilwar' 'americanfootbal'
 'americanfootballplay' 'amid' 'amidst' 'amnesia' 'amp' 'amsterdam' 'amus'
 'amusementpark' 'amy' 'amyadam' 'amysmart' 'ana' 'anakin' 'analyst'
 'anarchiccomedi' 'ancient' 'ancientrom' 'ancientworld' 'anderson' 'andi'
 'andiemacdowel' 'andrew' 'android' 'andy' 'andygarcía' 'angel' 'angela'
 'angelabassett' 'angeles' 'angelinajoli' 'anger' 'angle' 'angri' 'ani'
 'anim' 'animalattack' 'animalhorror' 'animals' 'anjelicahuston' 'ann'
 'anna' 'annafari' 'annakendrick' 'anne' 'annehathaway' 'annemoss'
 'annetteben' 'anni' 'annie' 'anniversari' 'announc' 'annual' 'anonym'
 'anoth' 'answer' 'ant' 'antholog' 'anthoni' 'anthonyanderson'
 'anthonyhopkin' 'anthonymacki' 'anthropomorph' 'anti' 'antic' 'antihero'
 'antiqu' 'antoinefuqua' 'antoniobandera' 'antonyelchin' 'anyon' 'anyth'
 'apart' 'apartheid' 'apartment' 'ape' 'apocalyps' 'apocalypse'
 'apocalypt' 'appar' 'appear' 'appl' 'apple' 'appoint' 'appreci'
 'apprentic' 'approach' 'april' 'aquarium' 'arab' 'arch' 'archaeologist'
 'archeolog' 'archer' 'architect' 'arctic' 'area' 'aren' 'arena'
 'argument' 'aris' 'aristocrat' 'arm' 'armi' 'armor' 'armsdeal' 'army'
 'arnold' 'arnoldschwarzenegg' 'arrang' 'arrangedmarriag' 'arrest' 'arriv'
 'arrog' 'art' 'arthur' 'artifact' 'artifici' 'artificialintellig'
 'artist' 'ash' 'ashley' 'ashleyjudd' 'ashtonkutch' 'asia' 'asian' 'asid'
 'ask' 'aspect' 'aspir' 'assassin' 'assault' 'assembl' 'assign' 'assist'
 'assistant' 'associ' 'assum' 'asteroid' 'astronaut' 'asylum' 'atheist'
 'athlet' 'atom' 'atomicbomb' 'attack' 'attacks' 'attempt'
 'attempttoescap' 'attend' 'attent' 'attic' 'attitud' 'attorney' 'attract'
 'auction' 'audienc' 'audit' 'august' 'aunt' 'austin' 'australia'
 'australian' 'author' 'autism' 'auto' 'automobilerac' 'aveng' 'averag'
 'avoid' 'await' 'awak' 'awaken' 'awar' 'award' 'away' 'awkward' 'awri'
 'awry' 'ax' 'babe' 'babi' 'baby' 'bachelor' 'backdrop' 'background'
 'backpack' 'bad' 'bag' 'bahama' 'bail' 'balanc' 'ball' 'ballet' 'balloon'
 'baltimor' 'ban' 'band' 'bandit' 'bangkok' 'banish' 'bank' 'banker'
 'bankrobb' 'bankrobberi' 'bar' 'barbrastreisand' 'bare' 'bargain' 'barn'
 'barney' 'baron' 'barri' 'barrylevinson' 'barrysonnenfeld' 'bas' 'base'
 'basebal' 'basedoncomicbook' 'basedongraphicnovel' 'basedonnovel'
 'basedonplay' 'basedonstagemus' 'basedontrueev' 'basedontruestori'
 'basedontvseri' 'basedonvideogam' 'basedonyoungadultnovel' 'basement'
 'basketbal' 'basketball' 'bat' 'batman' 'battl' 'battle' 'battlefield'
 'bay' 'beach' 'beam' 'bear' 'beard' 'beast' 'beat' 'beauti' 'beautiful'
 'beautifulwoman' 'beauty' 'becam' 'becaus' 'becki' 'becom'
 'becominganadult' 'bed' 'bedroom' 'bee' 'beer' 'befor' 'befriend' 'began'
 'begin' 'begins' 'behavior' 'belief' 'believ' 'bell' 'bella' 'belong'
 'belov' 'ben' 'benaffleck' 'bend' 'beneath' 'benefit' 'benfost'
 'beniciodeltoro' 'benjamin' 'benjaminbratt' 'benkingsley' 'bennett'
 'benstil' 'bent' 'berlin' 'best' 'bestfriend' 'bestfriendsinlov' 'bet'
 'beth' 'betray' 'bettemidl' 'better' 'betti' 'beverli' 'bibl' 'bid' 'big'
 'bigger' 'biggest' 'bike' 'biker' 'bikini' 'billhad' 'billi' 'billionair'
 'billmurray' 'billnighi' 'billpaxton' 'billpullman']

In [32]:
from sklearn.metrics.pairwise import cosine_similarity

In [33]:
similarity = cosine_similarity(vectors)

In [34]:
print(similarity)

[[1.         0.08346223 0.0860309  ... 0.04499213 0.         0.        ]
 [0.08346223 1.         0.06063391 ... 0.02378257 0.         0.02615329]
 [0.0860309  0.06063391 1.         ... 0.02451452 0.         0.        ]
 ...
 [0.04499213 0.02378257 0.02451452 ... 1.         0.03962144 0.04229549]
 [0.         0.         0.         ... 0.03962144 1.         0.08714204]
 [0.         0.02615329 0.         ... 0.04229549 0.08714204 1.        ]]

In [35]:
similarity.shape

(4806, 4806)

In [36]:
similarity[0]

array([1.        , 0.08346223, 0.0860309 , ..., 0.04499213, 0.        ,
       0.        ])

In [45]:
def recommend(movie, top_n=5):
  movie_index=new_df[new_df['title']==movie].index[0]
  distances=similarity[movie_index]
  movies_list=sorted(list(enumerate(distances)),reverse=True, key=lambda x:x[1])

  recommended_movies_list = []
  for i in movies_list[1:top_n+1]:
    recommended_movies_list.append(new_df.iloc[i[0]].title)
  return recommended_movies_list

In [38]:
recommend('Batman Begins')

The Dark Knight
Batman
Batman
The Dark Knight Rises
10th & Wolf

In [39]:
movie_genres = {}

for _, row in movies.iterrows():
    movie_genres[row['title']] = set(row['genres'])

In [40]:
def genre_overlap_score(query_movie, recommended_movies):
    query_genres = movie_genres[query_movie]

    scores = []
    for movie in recommended_movies:
        overlap = query_genres.intersection(movie_genres[movie])
        score = len(overlap) / len(query_genres) if query_genres else 0
        scores.append(score)

    return scores

In [41]:
def precision_at_k(query_movie, recommended_movies, k=5):
    query_genres = movie_genres[query_movie]
    hits = 0

    for movie in recommended_movies[:k]:
        if query_genres.intersection(movie_genres[movie]):
            hits += 1

    return hits / k

In [42]:
def hit_rate(query_movie, recommended_movies):
    query_genres = movie_genres[query_movie]

    for movie in recommended_movies:
        if query_genres.intersection(movie_genres[movie]):
            return 1
    return 0

In [46]:
query_movie = "Avatar"   # change this if needed

recommended_movies = recommend(query_movie, top_n=5)

print("Query Movie:", query_movie)
print("Recommended Movies:", recommended_movies)
print("Precision@5:", precision_at_k(query_movie, recommended_movies, k=5))
print("Genre Overlap Scores:", genre_overlap_score(query_movie, recommended_movies))
print("Hit Rate:", hit_rate(query_movie, recommended_movies))

Query Movie: Avatar
Recommended Movies: ['Aliens vs Predator: Requiem', 'Aliens', 'Falcon Rising', 'Independence Day', 'Titan A.E.']
Precision@5: 1.0
Genre Overlap Scores: [0.9333333333333333, 0.8, 0.8, 0.9, 0.9333333333333333]
Hit Rate: 1